Delete non-protected pod when Eviction API returns any kind of errors
cybozu-go/cke pull request #482
Opened 2021-09-29 08:58 UTC by masa213f

When there is misconfiguration of PodDisruptionBudgets, the Eviction API returns a 500 Internal Server Error response.
Even in this case, delete non-protected pods.

Signed-off-by: Masayuki Ishii <masa213f@gmail.com>

2021-09-29 09:26 UTC, zoetrope commented on op/reboot.go
> +			})
The same kind of log appears to be output twice 🤔

2021-09-29 09:26 UTC, zoetrope approved these changes
LGTM

2021-09-30 04:51 UTC, yokaze requested changes

2021-09-30 04:51 UTC, yokaze commented on op/reboot.go
> +func verifyJobManagedPod(ctx context.Context, cs *kubernetes.Clientset, n *cke.Node) error {
```suggestion
func checkJobPodNotExist(ctx context.Context, cs *kubernetes.Clientset, n *cke.Node) error {
```

2021-09-30 04:51 UTC, yokaze commented on op/reboot.go
> +		err := verifyJobManagedPod(ctx, cs, n)
```suggestion
		err := checkJobPodNotExist(ctx, cs, n)
```

2021-10-01 02:40 UTC, yokaze approved these changes
LGTM

2021-10-01 02:45 UTC, merged