use term package instead of gopass
cybozu-go/cke pull request #511
Opened 2021-11-09 08:29 UTC by umezawatakeshi

Signed-off-by: UMEZAWA Takeshi <takeshi-umezawa@cybozu.co.jp>

2021-11-09 10:30 UTC, morimoto-cybozu requested changes

2021-11-09 10:30 UTC, morimoto-cybozu commented on pkg/ckecli/cmd/vault_init.go
> +	defer term.Restore(0, oldState)
The godoc recommends not to use 0.
https://pkg.go.dev/golang.org/x/term#pkg-overview

```suggestion
	defer term.Restore(int(os.Stdin.Fd()), oldState)
```

2021-11-09 10:30 UTC, morimoto-cybozu commented on pkg/ckecli/cmd/vault_init.go
> +	p, err := t.ReadPassword(prompt)
A new terminal does not seem necessary.
I'm not sure whether `MakeRaw()` is necessary or not.

```suggestion
	fmt.Print(prompt)
	p, err := term.ReadPassword(int(os.Stdin.Fd()))
```

2021-11-10 06:54 UTC, umezawatakeshi commented on pkg/ckecli/cmd/vault_init.go
> +	p, err := t.ReadPassword(prompt)
according to my local poc just now, we have to print '\n' after ReadPassword. i.e. the following is enough:
```
	fmt.Print(prompt)
	p, err := term.ReadPassword(int(os.Stdin.Fd()))
	fmt.Println()
```

`MakeRaw` is required if we use `t.ReadPassword` but it does not seems required if we use `term.ReadPassword`.

2021-11-11 07:19 UTC, morimoto-cybozu approved these changes
LGTM

2021-11-11 07:19 UTC, merged