Stop using deprecated --register-with-taints option
cybozu-go/cke pull request #557
Opened 2022-08-04 05:09 UTC by masa213f

Signed-off-by: Masayuki Ishii <masa213f@gmail.com>

2022-08-08 08:40 UTC, morimoto-cybozu requested changes

2022-08-08 08:40 UTC, morimoto-cybozu commented on docs/cluster.md
> +When same taints are specified in both `boot_taints` (KubeletParams) and `RegisterWithTaints` (KubeletConfiguration), CKE respects `boot_taints`.
```suggestion
When taints with the same key are specified in both `boot_taints` (KubeletParams) and `RegisterWithTaints` (KubeletConfiguration), CKE respects `boot_taints`.
```

2022-08-08 08:44 UTC, morimoto-cybozu approved these changes
LGTM

2022-08-09 00:50 UTC, kmdkuk approved these changes

2022-08-09 01:14 UTC, merged