cke-tools: Update CNI plugins to v1.3.0
cybozu-go/cke pull request #646
Opened 2023-07-11 03:26 UTC by yokaze

Signed-off-by: Daichi Sakaue <daichi-sakaue@cybozu.co.jp>

2023-07-18 07:01 UTC, masa213f requested changes
How did you update `sabakan/mock/{generated.go, models.go}`?
If possible, please check for updates to the auto-generated files in CI.

2023-07-18 12:18 UTC, yokaze commented on mtest/Makefile
>  CT_VERSION = 0.9.0
@masa213f The version 0.9.4 of the ct does not have its binaries in the release, so we can only use v0.9.3.

2023-07-19 01:07 UTC, masa213f commented on Makefile
> +	go get github.com/99designs/gqlgen@"$$(go list -m github.com/99designs/gqlgen | cut -d' ' -f2)"
In any case, we need to comment on this. Either is fine. :)

2023-07-19 01:07 UTC, masa213f approved these changes

2023-07-19 05:37 UTC, masa213f approved these changes
LGTM

2023-07-19 06:04 UTC, merged