Extend cluster configuration for repair operations
cybozu-go/cke pull request #692
Opened 2023-12-25 12:29 UTC by morimoto-cybozu

Signed-off-by: morimoto-cybozu <kenji_morimoto@cybozu.co.jp>

2024-01-15 04:39 UTC, zeroalphat approved these changes
LGTM

2024-01-17 01:44 UTC, zeroalphat submitted a review, later dismissed
LGTM

2024-01-19 06:39 UTC, masa213f requested changes
I'm sorry for the delayed review.

2024-01-19 06:39 UTC, masa213f commented on op/status.go
> +		if !(entry.Status == cke.RepairStatusQueued || entry.Status == cke.RepairStatusProcessing) {
I thinsk this is easier to understand the meaning.

```suggestion
		if entry.HaveFinished() {
```

2024-01-24 08:57 UTC, masa213f commented on op/repair_drain_timeout.go
> +	entry.Status = cke.RepairStatusProcessing
Thank you for the description. I understood.

When a node's repair waits for the drain in step 2, the CKE will execute the other node's repair.
And then, more entries than "max_concurrent_repairs" will be in the "processing" status.

2024-01-24 08:58 UTC, masa213f submitted a review, later dismissed

2024-01-24 23:57 UTC, YZ775 approved these changes
LGTM

2024-01-25 00:43 UTC, zeroalphat approved these changes
LGTM

2024-01-25 06:42 UTC, merged