Non-Graceful Node Shutdown before deleting k8s node
cybozu-go/cke pull request #753
Opened 2024-07-08 02:15 UTC by YZ775

2024-12-06 09:17 UTC, morimoto-cybozu requested changes
This feature seems to work perfectly!

I added comments just for clarity.

2024-12-06 09:17 UTC, morimoto-cybozu commented on docs/repair.md
> +`success_command` and its timeout are used when all of the repair steps are successfully finished.
This description seems misleading.
CKE in this PR will execute `success_command` when it finds that `health_check_command` returns `true`.
* CKE will abort the sequence of the repair steps if the machine gets healthy; not all of the repair steps are executed.
* Even when all of the repair steps finish successfully, the machine may still be unhealthy.

```suggestion
`success_command` and its timeout are used when the machine is evaluated as healthy and the repair operation finishes successfully.
```

2024-12-06 09:17 UTC, morimoto-cybozu commented on docs/repair.md
> +If the repair is failed, the command is not executed.
```suggestion
If the repair operation has failed, the command is not executed.
```

2024-12-09 02:07 UTC, YZ775 commented
@morimoto-cybozu
Thank you for your review. 
I fixed the code and document.

2024-12-09 05:25 UTC, morimoto-cybozu approved these changes

2024-12-09 08:13 UTC, merged